<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

    <p>
    <div class="field twilio_image required">
        <label for="twilio_image" class="label"><span><?php /* @escapeNotVerified */
                echo __('Image') ?></span></label>
        <div class="control">
            <input type="file" name="twilio_image" id="twilio_image" title="<?php /* @escapeNotVerified */
            echo __('Image') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>