<script>
    function goBack() {
        window.history.back()
    }
</script>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                class="action-secondary back"
                title="<?php echo __('Back') ?>"
                onclick="goBack()">
                <?php echo __('Back'); ?>
            </button>
        </div>
    </div>
</div>