<!--<fieldset class="fieldset create account" data-hasrequired="--><?php ///* @escapeNotVerified */
//echo __('* Required Fields') ?><!--">-->
<!--    <legend class="legend">-->
<!--        <span>-->
<!--        --><?php
//        /* @escapeNotVerified */
//        echo __('Avatar')
//        ?>
<!--        </span>-->
<!--    </legend>-->
    <!--    twilio_image-->
<div class="box box-avatar">
    <strong class="box-title"><span>Avatar</span></strong>
    <p>
        <?php if ($logo = $block->getLogoUrl()): ?>
            <img src="<?php echo $logo; ?>"  />
        <?php endif; ?>
       </p>

</div>
<!--</fieldset>-->